apiVersion: v1
kind: Service
metadata:
  name: backend-examination-service
  namespace: apps
spec:
  selector:
    app: backend-examination
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP